# Generated by Django 2.2.4 on 2023-09-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20230920_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bill',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
