# Generated by Django 2.2.4 on 2023-09-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20230920_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
