# Generated by Django 2.2.4 on 2023-09-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.SmallIntegerField(),
        ),
    ]
