# Generated by Django 2.2.4 on 2023-09-21 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20230920_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered',
            field=models.DateField(blank=True, null=True),
        ),
    ]
