# Generated by Django 2.2.4 on 2023-09-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20230921_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='document',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='bill',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
